ALTER TABLE app_settings
  ADD COLUMN vlm_model VARCHAR(100) NOT NULL DEFAULT 'qwen2.5vl:7b',
  ADD COLUMN vlm_device VARCHAR(10)  NOT NULL DEFAULT 'auto',
  ADD COLUMN vlm_num_ctx INTEGER     NOT NULL DEFAULT 4096,
  ADD COLUMN vlm_num_thread INTEGER  NOT NULL DEFAULT 4;
